// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWQs-hKU3PinNaDyUodiNI9QK7YdNhbg',
    appId: '1:804873166790:web:5b9e56dfd9e63b429c1cc7',
    messagingSenderId: '804873166790',
    projectId: 'parking-gestion-urbana',
    authDomain: 'parking-gestion-urbana.firebaseapp.com',
    databaseURL: 'https://parking-gestion-urbana-default-rtdb.firebaseio.com',
    storageBucket: 'parking-gestion-urbana.firebasestorage.app',
    measurementId: 'G-94MLNVCHXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvP0K_v2a_Sbo3NWSmMS1CQn7x9qj75s8',
    appId: '1:804873166790:android:62af92dbfb3b3ac19c1cc7',
    messagingSenderId: '804873166790',
    projectId: 'parking-gestion-urbana',
    databaseURL: 'https://parking-gestion-urbana-default-rtdb.firebaseio.com',
    storageBucket: 'parking-gestion-urbana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD748Sh-4KamkRKgWPbEwWhLpViu_5GXoA',
    appId: '1:804873166790:ios:909a819204e83be39c1cc7',
    messagingSenderId: '804873166790',
    projectId: 'parking-gestion-urbana',
    databaseURL: 'https://parking-gestion-urbana-default-rtdb.firebaseio.com',
    storageBucket: 'parking-gestion-urbana.firebasestorage.app',
    iosClientId: '804873166790-lijjovpevp3uj4smssi1dd5h3d9e53vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appUserParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD748Sh-4KamkRKgWPbEwWhLpViu_5GXoA',
    appId: '1:804873166790:ios:909a819204e83be39c1cc7',
    messagingSenderId: '804873166790',
    projectId: 'parking-gestion-urbana',
    databaseURL: 'https://parking-gestion-urbana-default-rtdb.firebaseio.com',
    storageBucket: 'parking-gestion-urbana.firebasestorage.app',
    iosClientId: '804873166790-lijjovpevp3uj4smssi1dd5h3d9e53vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appUserParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYWQs-hKU3PinNaDyUodiNI9QK7YdNhbg',
    appId: '1:804873166790:web:c4556d863f4b1c4a9c1cc7',
    messagingSenderId: '804873166790',
    projectId: 'parking-gestion-urbana',
    authDomain: 'parking-gestion-urbana.firebaseapp.com',
    databaseURL: 'https://parking-gestion-urbana-default-rtdb.firebaseio.com',
    storageBucket: 'parking-gestion-urbana.firebasestorage.app',
    measurementId: 'G-PW4NTM6Y24',
  );
}
